// client/src/routes/login/+page.svelte
<script lang="ts">
    import { loginUser } from "$lib/api";
    import Logo from "../../components/Logo.svelte";
    import { goto } from "$app/navigation";
  import { onMount } from "svelte";

    let credential="", password="", visible=false, theme="";

    async function handleLogin(e: Event) {
        e.preventDefault();
        const result=await loginUser({ credential, password });
        if(result.token) {
            goto("/home");
        } else {
            alert(result.message);
        }
    };

    onMount(()=>{
        theme=localStorage.getItem("theme") || "dark";
    })

</script>

<div class="login-page">
    <img class="login-image" src="/community.png" alt="community">
    <form class="login-form" on:submit={handleLogin}>
        <h1>Login</h1>
        <div class="login-input">
            <label for="credential">Email or Username</label>
            <input type="text" id="credential" bind:value={credential} placeholder="Alexander" required>
        </div>
        <div class="login-input">
            <label for="password">Password</label>
            <div class="login-password">
                <input type={visible ? "text" : "password"} id="password" bind:value={password} placeholder="Password" required>
                <button type="button" on:click={()=>visible=!visible} class="eye">
                    <img src={visible ? theme==="light" ? "/eye.png" : "/eye-white.png" : theme==="light" ? "/eye-crossed.png" : "/eye-crossed-white.png"} alt="eye">
                </button>
            </div>
        </div>
        <button type="submit" class="login-button">Login</button>
        <p>Don't have an account? <a href="/register">Register</a></p>
    </form>
</div>

<Logo/>

<style>
    .login-page{
        display: flex;
        height: 100vh;
        padding: 8px;
        gap: 8px;
        background-color: var(--bg1);
        color: var(--text1);
    }

    .login-image { 
        width: calc(50% - 4px);
        object-fit: cover;
        border-radius: 8px;
    }

    .login-form {
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 16px 10%;
        width: 50%;
        height: 100%;
        gap: 16px;
        border-radius: 8px;
    }

    input {
        padding: 16px;
        background-color: var(--bg3);
        color: var(--text1);
        border: 1px solid var(--bg1);
        outline: none;
        font-size: 16px;
        border-radius: 8px;
    }

    .login-password input{
        border: none;
        width: 100%;
    }

    input:focus{
        border: 1px solid var(--orange);
    }

    .login-password input:focus{
        border: none;
    }

    .login-input{
        display: flex;
        flex-direction: column;
        gap: 8px;
    }

    .login-password{
        display: flex;
        align-items: center;
        width: 100%;
        position: relative;
        border: 1px solid var(--bg1);
        border-radius: 8px;
    }

    .login-password:focus-within{
        border: 1px solid var(--orange);
    }

    .eye{
        background-color: var(--bg3);
        border: none;
        display: flex;
        position: absolute;
        cursor: pointer;
        right: 16px;
    }
    
    .eye img{
        width: 24px;
        height: 24px;
    }

    p{
        margin: 0 auto;
    }
    
    a{
        text-decoration: underline;
        color: var(--text1);
    }

    a:hover{
        color: var(--orange);
    }

    .login-button{
        padding: 16px;
        font-size: 16px;
        background-color: var(--text1);
        color: var(--bg1);
        border: 1px solid var(--bg1);
        outline: none;
        cursor: pointer;
        border-radius: 8px;
    }

    .login-button:hover{
        color: var(--white);
        background-color: var(--orange);
    }

    @media(max-width: 1080px){
        .login-form{
            padding: 16px;
        }
    }

    @media(max-width: 600px){
        .login-image{
            display: none;
        }

        .login-form{
            width: 100%;
        }
    }

    @media(max-width: 400px){
        .login-page{
            margin: 0;
            border: none;
            height: 100vh;
        }
    }
</style>

// client/src/pages/auth/login/Login.tsx
import React, { useEffect, useState } from "react";
import "./login.css";
import { useNavigate } from "react-router-dom";
import Logo from "../../../components/logo/Logo";

interface loginDataType{
    credential: string,
    password: string
}

export default function Login(){
    const API_URL=import.meta.env.VITE_APP_API_URL;
    const navigate=useNavigate();

    const [loginData, setLoginData]=useState<loginDataType>({
        credential: "",
        password: ""
    });
    const [visible, setVisible]=useState(false);
    const [theme, setTheme]=useState("dark");
    
    useEffect(()=>{
        const savedTheme=localStorage.getItem("theme") || "dark";
        setNewTheme(savedTheme);
    }, []);

    const setNewTheme=(newTheme: string)=>{
        setTheme(newTheme);
        document.body.classList.toggle("light-mode", newTheme==="light");
        document.documentElement.setAttribute("data-theme", newTheme);
        localStorage.setItem("theme", newTheme);
    };

    async function loginUser(e: React.FormEvent<HTMLFormElement>){
        e.preventDefault();
        try{
            const response=await fetch(`${API_URL}/login`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(loginData),
                credentials: "include"
            });
            const result=await response.json();
            if(response.ok){
                navigate("/home");
            }
            console.log(result.message);
        }
        catch(error){
            console.log(error);
        }
    }

    function handleInputChange(e: React.ChangeEvent<HTMLInputElement>){
        setLoginData({
            ...loginData,
            [e.target.name]: e.target.value
        })
    }

    return(
        <>
        <Logo/>
        <div className="login-page">
            <img src="/community.png" alt="community"/>
            <form className="login-form" onSubmit={loginUser}>
                <h1>Login</h1>
                <div className="login-input">
                    <label htmlFor="credential">Email or Username</label>
                    <input type="text" id="credential" name="credential" value={loginData.credential} onChange={handleInputChange} placeholder="alexander@gmail.com" required/>
                </div>
                <div className="login-input">
                    <label htmlFor="password">Password</label>
                    <div className="login-password">
                        <input type={visible ? "text" : "password"} id="password" name="password" value={loginData.password} onChange={handleInputChange} placeholder="Password" required/>
                        <button type="button" onClick={()=>setVisible(visible=>!visible)}>
                            <img src={visible ? theme==="light" ? "/eye.png" : "/eye-white.png" : theme==="light" ? "/eye-crossed.png" : "/eye-crossed-white.png"} alt="eye"/>
                        </button>
                    </div>
                </div>
                <button type="submit" className="login-button">Login</button>
                <p>Don't have an account? <a href="/register">Register</a></p>
            </form>
        </div>
        </>
    )
}
